downgrade parboiled to version used by NetLogo 5.3
(#101)

Having the newer parboiled created a conflict in
asm-all version, resulting in

    java.lang.NoSuchMethodError: org.objectweb.asm.tree.ClassNode

when trying to use parboiled for url parsing in the url tests.

Strangely, it worked locally and was only failing on Travis.